# keep in sync with
# src/main/resources/templates/haskell/exercise/stack.yaml
# src/main/resources/templates/haskell/solution/stack.yaml
# src/main/resources/templates/haskell/test/stack.yaml
resolver: lts-19.13

packages: []
